"""Turn stitched intensity volumes into portable, shaded PLY surface meshes."""

from pathlib import Path

import numpy as np
from scipy.ndimage import gaussian_filter
from skimage.filters import threshold_otsu
from skimage.measure import marching_cubes


def _surface_colour(vertices, normals):
    """Return a subtle depth-and-lighting colour for each mesh vertex."""
    depth = vertices[:, 0]
    spread = np.ptp(depth)
    depth = (depth - depth.min()) / spread if spread else np.zeros_like(depth)
    light = np.clip(0.35 + 0.65 * np.abs(normals[:, 2]), 0, 1)
    base = np.column_stack((35 + 30 * depth, 125 + 85 * depth, 190 + 45 * depth))
    return np.clip(base * light[:, None], 0, 255).astype(np.uint8)


def volume_to_mesh(volume, level=None, smoothing_sigma=1.0, step_size=1, spacing=(1, 1, 1)):
    """Extract a smoothed isosurface from a 3-D stitched volume.

    ``level=None`` uses Otsu's threshold, which avoids baking a dataset-specific
    intensity threshold into the stitcher.  ``spacing`` is Z/Y/X voxel spacing
    and is written into the mesh coordinates.
    """
    image = np.asarray(volume, dtype=np.float32)
    if image.ndim != 3:
        raise ValueError(f"Expected a 3-D volume, got shape {image.shape}")
    finite = image[np.isfinite(image)]
    if finite.size == 0 or finite.max() <= finite.min():
        raise ValueError("The stitched volume needs a non-constant finite intensity range")
    if smoothing_sigma < 0:
        raise ValueError("smoothing_sigma must be non-negative")
    if step_size < 1:
        raise ValueError("step_size must be at least 1")

    image = np.nan_to_num(image, nan=0.0, posinf=finite.max(), neginf=finite.min())
    if smoothing_sigma:
        image = gaussian_filter(image, sigma=smoothing_sigma)
    if level is None:
        level = float(threshold_otsu(image))
    if not image.min() < level < image.max():
        raise ValueError(f"Surface level {level} must be between {image.min()} and {image.max()}")

    # Do not pad the volume. Padding closes intensity that touches the scan
    # boundary with artificial side walls and caps, making the mesh look like
    # it is trapped in a box. The acquired surface should remain open at scan
    # boundaries; its real bottom panel is preserved by marching cubes itself.
    vertices, faces, normals, _ = marching_cubes(
        image, level=level, spacing=spacing, step_size=step_size,
        gradient_direction="descent", allow_degenerate=False,
    )
    return vertices.astype(np.float32), faces.astype(np.int32), normals.astype(np.float32), level


def save_ply(vertices, faces, normals, filename, colours=None):
    """Write a binary little-endian PLY mesh with normals and vertex colours."""
    vertices = np.asarray(vertices, dtype=np.float32)
    faces = np.asarray(faces, dtype=np.int32)
    normals = np.asarray(normals, dtype=np.float32)
    if vertices.ndim != 2 or vertices.shape[1] != 3 or normals.shape != vertices.shape:
        raise ValueError("vertices and normals must each have shape (N, 3)")
    if faces.ndim != 2 or faces.shape[1] != 3:
        raise ValueError("faces must have shape (M, 3)")
    if colours is None:
        colours = _surface_colour(vertices, normals)
    colours = np.asarray(colours, dtype=np.uint8)
    if colours.shape != vertices.shape:
        raise ValueError("colours must have shape (N, 3)")

    path = Path(filename)
    if path.suffix.lower() != ".ply":
        raise ValueError(f"PLY output must use a .ply filename, got {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    vertex_data = np.empty(len(vertices), dtype=np.dtype([
        ("x", "<f4"), ("y", "<f4"), ("z", "<f4"),
        ("nx", "<f4"), ("ny", "<f4"), ("nz", "<f4"),
        ("red", "u1"), ("green", "u1"), ("blue", "u1"),
    ]))
    vertex_data["x"], vertex_data["y"], vertex_data["z"] = vertices.T
    vertex_data["nx"], vertex_data["ny"], vertex_data["nz"] = normals.T
    vertex_data["red"], vertex_data["green"], vertex_data["blue"] = colours.T
    face_data = np.empty(len(faces), dtype=np.dtype([("count", "u1"), ("indices", "<i4", (3,))]))
    face_data["count"] = 3
    face_data["indices"] = faces

    header = f"""ply
format binary_little_endian 1.0
comment generated by imes4d
element vertex {len(vertices)}
property float x
property float y
property float z
property float nx
property float ny
property float nz
property uchar red
property uchar green
property uchar blue
element face {len(faces)}
property list uchar int vertex_indices
end_header
"""
    with path.open("wb") as handle:
        handle.write(header.encode("ascii"))
        vertex_data.tofile(handle)
        face_data.tofile(handle)


def export_volume_as_ply(volume, output, level=None, smoothing_sigma=1.0, step_size=1, spacing=(1, 1, 1)):
    """Extract and save a PLY mesh, returning its vertex/face counts and level."""
    vertices, faces, normals, level = volume_to_mesh(
        volume, level=level, smoothing_sigma=smoothing_sigma,
        step_size=step_size, spacing=spacing,
    )
    save_ply(vertices, faces, normals, output)
    return len(vertices), len(faces), level
